theme: jekyll-theme-minimal
title: LYWAUTm — Développeur Web
description: Portfolio, TP et fiches pratiques
title: TP GROUPE CUISINE
description: Travail de groupe (Yannick, Dorine et moi) sur la création d'un site web sur un thème à choirir parmi 3 dans un délai de 5 jours.
